Document: mycitadel
Title: Debian mycitadel Manual
Author: <insert document author here>
Abstract: This manual describes what mycitadel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mycitadel/mycitadel.sgml.gz

Format: postscript
Files: /usr/share/doc/mycitadel/mycitadel.ps.gz

Format: text
Files: /usr/share/doc/mycitadel/mycitadel.text.gz

Format: HTML
Index: /usr/share/doc/mycitadel/html/index.html
Files: /usr/share/doc/mycitadel/html/*.html
